export const POSTGRES_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS agent_room_schema_migrations (
  version integer PRIMARY KEY,
  applied_at bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_room_rooms (
  code text PRIMARY KEY,
  topic text NOT NULL,
  created_at bigint NOT NULL,
  created_by text NOT NULL,
  status text NOT NULL CHECK (status IN ('active', 'ended')),
  version integer NOT NULL CHECK (version >= 1),
  room_json jsonb NOT NULL,
  updated_at bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_room_messages (
  room_code text NOT NULL REFERENCES agent_room_rooms(code) ON DELETE CASCADE,
  sequence bigint NOT NULL,
  message_id bigint NOT NULL,
  message_json jsonb NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY (room_code, sequence),
  UNIQUE (room_code, message_id)
);

CREATE TABLE IF NOT EXISTS agent_room_task_boards (
  room_code text PRIMARY KEY REFERENCES agent_room_rooms(code) ON DELETE CASCADE,
  version integer NOT NULL CHECK (version >= 1),
  board_json jsonb NOT NULL,
  updated_at bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_room_minutes (
  room_code text NOT NULL REFERENCES agent_room_rooms(code) ON DELETE CASCADE,
  report_id text NOT NULL,
  report_json jsonb NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY (room_code, report_id)
);

CREATE TABLE IF NOT EXISTS agent_room_receipts (
  room_code text NOT NULL REFERENCES agent_room_rooms(code) ON DELETE CASCADE,
  receipt_id text NOT NULL,
  receipt_kind text NOT NULL CHECK (receipt_kind IN ('receipt', 'lease_event')),
  lease_event text CHECK (lease_event IS NULL OR lease_event IN
    ('granted', 'renewed', 'released', 'expired', 'handoff_requested')),
  receipt_json jsonb NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY (room_code, receipt_id)
);

CREATE INDEX IF NOT EXISTS agent_room_messages_room_created_idx
  ON agent_room_messages(room_code, created_at);
CREATE INDEX IF NOT EXISTS agent_room_receipts_room_created_idx
  ON agent_room_receipts(room_code, created_at);

INSERT INTO agent_room_schema_migrations (version, applied_at)
VALUES (1, (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::bigint)
ON CONFLICT (version) DO NOTHING;

CREATE TABLE IF NOT EXISTS agent_room_fleet_trust_keys (
  fleet_id text NOT NULL,
  key_id text NOT NULL,
  public_key_json jsonb NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY (fleet_id, key_id)
);

INSERT INTO agent_room_schema_migrations (version, applied_at)
VALUES (2, (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::bigint)
ON CONFLICT (version) DO NOTHING;

ALTER TABLE agent_room_receipts
  ADD COLUMN IF NOT EXISTS insertion_sequence bigint;

-- Exact insertion order for pre-migration created_at ties is unrecoverable. Give
-- legacy rows a deterministic order; the identity preserves true order afterward.
WITH legacy_order AS MATERIALIZED (
  SELECT room_code, receipt_id,
    row_number() OVER (ORDER BY created_at, receipt_id) AS insertion_sequence
  FROM agent_room_receipts
  WHERE insertion_sequence IS NULL
)
UPDATE agent_room_receipts AS receipts
SET insertion_sequence = legacy_order.insertion_sequence
FROM legacy_order
WHERE receipts.room_code = legacy_order.room_code
  AND receipts.receipt_id = legacy_order.receipt_id;

ALTER TABLE agent_room_receipts
  ALTER COLUMN insertion_sequence SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema()
      AND table_name = 'agent_room_receipts'
      AND column_name = 'insertion_sequence'
      AND is_identity = 'YES'
  ) THEN
    ALTER TABLE agent_room_receipts
      ALTER COLUMN insertion_sequence ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

DO $$
DECLARE
  sequence_name regclass := pg_get_serial_sequence('agent_room_receipts', 'insertion_sequence')::regclass;
  maximum_sequence bigint;
BEGIN
  SELECT max(insertion_sequence) INTO maximum_sequence FROM agent_room_receipts;
  IF maximum_sequence IS NULL THEN
    PERFORM setval(sequence_name, 1, false);
  ELSE
    PERFORM setval(sequence_name, maximum_sequence, true);
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS agent_room_receipts_room_sequence_idx
  ON agent_room_receipts(room_code, insertion_sequence);

INSERT INTO agent_room_schema_migrations (version, applied_at)
VALUES (3, (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::bigint)
ON CONFLICT (version) DO NOTHING;
`;
