ALTER TABLE agent_room_receipts
  ADD COLUMN IF NOT EXISTS insertion_sequence bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS agent_room_receipts_room_sequence_idx
  ON agent_room_receipts(room_code, insertion_sequence);

INSERT INTO agent_room_schema_migrations (version, applied_at)
VALUES (3, (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::bigint)
ON CONFLICT (version) DO NOTHING;
