ALTER TABLE agent_room_receipts
  ADD COLUMN IF NOT EXISTS insertion_sequence bigint;

-- Exact insertion order for pre-migration created_at ties is unrecoverable. Give
-- legacy rows a deterministic order; the identity preserves true order afterward.
WITH legacy_order AS MATERIALIZED (
  SELECT room_code, receipt_id,
    row_number() OVER (ORDER BY created_at, receipt_id) AS insertion_sequence
  FROM agent_room_receipts
  WHERE insertion_sequence IS NULL
)
UPDATE agent_room_receipts AS receipts
SET insertion_sequence = legacy_order.insertion_sequence
FROM legacy_order
WHERE receipts.room_code = legacy_order.room_code
  AND receipts.receipt_id = legacy_order.receipt_id;

ALTER TABLE agent_room_receipts
  ALTER COLUMN insertion_sequence SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema()
      AND table_name = 'agent_room_receipts'
      AND column_name = 'insertion_sequence'
      AND is_identity = 'YES'
  ) THEN
    ALTER TABLE agent_room_receipts
      ALTER COLUMN insertion_sequence ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

DO $$
DECLARE
  sequence_name regclass := pg_get_serial_sequence('agent_room_receipts', 'insertion_sequence')::regclass;
  maximum_sequence bigint;
BEGIN
  SELECT max(insertion_sequence) INTO maximum_sequence FROM agent_room_receipts;
  IF maximum_sequence IS NULL THEN
    PERFORM setval(sequence_name, 1, false);
  ELSE
    PERFORM setval(sequence_name, maximum_sequence, true);
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS agent_room_receipts_room_sequence_idx
  ON agent_room_receipts(room_code, insertion_sequence);

INSERT INTO agent_room_schema_migrations (version, applied_at)
VALUES (3, (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::bigint)
ON CONFLICT (version) DO NOTHING;
